### ISSUE TITLE
General question about this repository

### ISSUE THREAD

**Issue by ptmcgrat** [alexmrqt/gr-lazyviterbi#1]
Hello,

I'm interested in running an HMM on long (~100,000) sequences to decode ~10 different states. I can use a normal Viterbi algorithm to decode this. However, i'm interested in speeding up the processing and would like to try a lazy viterbi algorithm. This is one of the few open source modules i have found and would like to try this out. However, i'm completely unfamiliar with GNU Radio. I have tried playing around with the examples and i'm a bit stymied. I have a few questions i was hoping you could answer.

1. Could this be used to run a HMM to decode this data? My understanding is that GNU Radio is normally used on streaming data, however, in your example you seem to show how to create a stream from vector data.

2. Is it possible to specify the state model in your lazy viterbi class to contain multiple states with custom transition probabilities?

3. How do you grab the decoded data? Currently, in one of the examples, you use a null sink. Is the data stored there somehow? Do i need to use a different sink to grab the data to process? Any advice on how to do this?

THanks for any help you can give me.

**Comment by alexmrqt** [comment]
Hello,

Sorry for the late reply, I just got Internet back at home!

This module can definitely be used to decode data based on a HMM (though, certain types of HMM may be unsupported).
GNURadio examples usually show real-time processing, indeed, but off-line processing is possible using vector_source and vector_sink blocks (you can grab processed data using this instead of the null sink in my examples).

The main challenge is to translate your HMM into GNURadio's fsm... Which is unfortunately not very well documented yet (see https://gnuradio.org/doc/doxygen/classgr_1_1trellis_1_1fsm.html).
Personally, I like to store HMM in fsm files. The format is the following:

    I S O
    
    NS[0,0]   ...   NS[0,I-1]
      ...              ...
    NS[S-1,0] ...   NS[S-1,I-1]
    
    OS[0,0]   ...   OS[0,I-1]
      ...              ...
    OS[S-1,0] ...   OS[S-1,I-1]

Where I, S, O, NS and OS are described here: https://gnuradio.org/doc/doxygen/classgr_1_1trellis_1_1fsm.html.

Please let me know if you need anything else. I'd love to see this block being useful for someone!
